/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { PayableOverrides } from "../../common";
import type {
  ERC20ProtectionSlim,
  ERC20ProtectionSlimInterface,
} from "../../contracts/ERC20ProtectionSlim";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_primaryWallet",
        type: "address",
      },
      {
        internalType: "address",
        name: "_backupWallet",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_timelapse",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_delegate",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "DelegateCallFailed",
    type: "error",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "assetsTransferred",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "backupWallet",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "primaryWallet",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "timelapse",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x60806040526040516102fd3803806102fd8339810160408190526100229161009d565b600080546001600160a01b03199081166001600160a01b039687161790915560018054821694861694909417909355600291909155600380546001600160a81b03191661010033021790556004805490921692169190911790556100ea565b80516001600160a01b038116811461009857600080fd5b919050565b600080600080608085870312156100b357600080fd5b6100bc85610081565b93506100ca60208601610081565b9250604085015191506100df60608601610081565b905092959194509250565b610204806100f96000396000f3fe60806040526004361061004e5760003560e01c8063486c96fa146100ee578063c45a01551461012b578063db47010014610150578063e401765114610174578063fa52733a1461019457610055565b3661005557005b6004546040516000913691606091849182916001600160a01b03169061007e90839087906101be565b600060405180830381855af49150503d80600081146100b9576040519150601f19603f3d011682016040523d82523d6000602084013e6100be565b606091505b5091509150816100e1576040516318cecad560e01b815260040160405180910390fd5b8051945060200192505050f35b3480156100fa57600080fd5b5060005461010e906001600160a01b031681565b6040516001600160a01b0390911681526020015b60405180910390f35b34801561013757600080fd5b5060035461010e9061010090046001600160a01b031681565b34801561015c57600080fd5b5061016660025481565b604051908152602001610122565b34801561018057600080fd5b5060015461010e906001600160a01b031681565b3480156101a057600080fd5b506003546101ae9060ff1681565b6040519015158152602001610122565b818382376000910190815291905056fea264697066735822122099dc3bc9a32e6670642a1e7d416719f9e52e9e929e320d816f87b6f3996f54e364736f6c63430008180033";

type ERC20ProtectionSlimConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERC20ProtectionSlimConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERC20ProtectionSlim__factory extends ContractFactory {
  constructor(...args: ERC20ProtectionSlimConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _primaryWallet: AddressLike,
    _backupWallet: AddressLike,
    _timelapse: BigNumberish,
    _delegate: AddressLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(
      _primaryWallet,
      _backupWallet,
      _timelapse,
      _delegate,
      overrides || {}
    );
  }
  override deploy(
    _primaryWallet: AddressLike,
    _backupWallet: AddressLike,
    _timelapse: BigNumberish,
    _delegate: AddressLike,
    overrides?: PayableOverrides & { from?: string }
  ) {
    return super.deploy(
      _primaryWallet,
      _backupWallet,
      _timelapse,
      _delegate,
      overrides || {}
    ) as Promise<
      ERC20ProtectionSlim & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): ERC20ProtectionSlim__factory {
    return super.connect(runner) as ERC20ProtectionSlim__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC20ProtectionSlimInterface {
    return new Interface(_abi) as ERC20ProtectionSlimInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ERC20ProtectionSlim {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ERC20ProtectionSlim;
  }
}
