/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { PayableOverrides } from "../../common";
import type {
  NFTProtectionSlim,
  NFTProtectionSlimInterface,
} from "../../contracts/NFTProtectionSlim";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_primaryWallet",
        type: "address",
      },
      {
        internalType: "address",
        name: "_backupWallet",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_timelapse",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_delegate",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "DelegateCallFailed",
    type: "error",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "assetsTransferred",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "backupWallet",
    outputs: [
      {
        internalType: "address payable",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "isAssetProtected",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "primaryWallet",
    outputs: [
      {
        internalType: "address payable",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "timelapse",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x60806040526040516103353803806103358339810160408190526100229161009a565b600080546001600160a01b03199081166001600160a01b039687161790915560018054821694861694909417909355600980549093169316929092179055600255600380546001600160a81b03191661010033021790556100e7565b80516001600160a01b038116811461009557600080fd5b919050565b600080600080608085870312156100b057600080fd5b6100b98561007e565b93506100c76020860161007e565b9250604085015191506100dc6060860161007e565b905092959194509250565b61023f806100f66000396000f3fe60806040526004361061004e5760003560e01c8063486c96fa146100ee578063db4701001461012b578063e40176511461014f578063f3cc92141461016f578063fa52733a146101af57610055565b3661005557005b6009546040516000913691606091849182916001600160a01b03169061007e90839087906101c9565b600060405180830381855af49150503d80600081146100b9576040519150601f19603f3d011682016040523d82523d6000602084013e6100be565b606091505b5091509150816100e1576040516318cecad560e01b815260040160405180910390fd5b8051945060200192505050f35b3480156100fa57600080fd5b5060005461010e906001600160a01b031681565b6040516001600160a01b0390911681526020015b60405180910390f35b34801561013757600080fd5b5061014160025481565b604051908152602001610122565b34801561015b57600080fd5b5060015461010e906001600160a01b031681565b34801561017b57600080fd5b5061019f61018a3660046101d9565b60066020526000908152604090205460ff1681565b6040519015158152602001610122565b3480156101bb57600080fd5b5060035461019f9060ff1681565b8183823760009101908152919050565b6000602082840312156101eb57600080fd5b81356001600160a01b038116811461020257600080fd5b939250505056fea2646970667358221220ba39901fd6b0747d243f9c8a454eb90b749ea647b08c64871e53827effbbf8bd64736f6c63430008180033";

type NFTProtectionSlimConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NFTProtectionSlimConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class NFTProtectionSlim__factory extends ContractFactory {
  constructor(...args: NFTProtectionSlimConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _primaryWallet: AddressLike,
    _backupWallet: AddressLike,
    _timelapse: BigNumberish,
    _delegate: AddressLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(
      _primaryWallet,
      _backupWallet,
      _timelapse,
      _delegate,
      overrides || {}
    );
  }
  override deploy(
    _primaryWallet: AddressLike,
    _backupWallet: AddressLike,
    _timelapse: BigNumberish,
    _delegate: AddressLike,
    overrides?: PayableOverrides & { from?: string }
  ) {
    return super.deploy(
      _primaryWallet,
      _backupWallet,
      _timelapse,
      _delegate,
      overrides || {}
    ) as Promise<
      NFTProtectionSlim & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): NFTProtectionSlim__factory {
    return super.connect(runner) as NFTProtectionSlim__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NFTProtectionSlimInterface {
    return new Interface(_abi) as NFTProtectionSlimInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): NFTProtectionSlim {
    return new Contract(address, _abi, runner) as unknown as NFTProtectionSlim;
  }
}
