import { Theme } from "@rainbow-me/rainbowkit"

export const customThemeRainbowKit: Theme = {
  blurs: {
    modalOverlay: "#F5F7FF",
  },
  colors: {
    accentColor: "#0a208b",
    accentColorForeground: "#fff",
    actionButtonBorder: "#fff",
    actionButtonBorderMobile: "",
    actionButtonSecondaryBackground: "",
    closeButton: "",
    closeButtonBackground: "#7b7e84",
    connectButtonBackground: "",
    connectButtonBackgroundError: "",
    connectButtonInnerBackground: "",
    connectButtonText: "#F3F3FA",
    connectButtonTextError: "",
    connectionIndicator: "#51E48C",
    downloadBottomCardBackground: "",
    downloadTopCardBackground: "",
    error: "#ff7373",
    generalBorder: "",
    generalBorderDim: "",
    menuItemBackground: "#F3F3FA",
    modalBackdrop: "rgba(10, 32, 139, 0.3)",
    modalBackground: "#fff",
    modalBorder: "",
    modalText: "#3e4555",
    modalTextDim: "#3e4555",
    modalTextSecondary: "#3e4555",
    profileAction: "#fff",
    profileActionHover: "",
    profileForeground: "#F3F3FA",
    selectedOptionBorder: "#F3F3FA",
    standby: "",
  },
  fonts: {
    body: "",
  },
  radii: {
    actionButton: "24px",
    connectButton: "24px",
    menuButton: "16px",
    modal: "24px",
    modalMobile: "24px",
  },
  shadows: {
    connectButton: "0px 8px 24px 0px rgba(10, 32, 139, 0.05)",
    dialog: "0px 8px 24px 0px rgba(10, 32, 139, 0.05)",
    profileDetailsAction: "0px 8px 24px 0px rgba(10, 32, 139, 0.05)",
    selectedOption: "0px 8px 24px 0px rgba(10, 32, 139, 0.05)",
    selectedWallet: "0px 8px 24px 0px rgba(10, 32, 139, 0.05)",
    walletLogo: "0px 8px 24px 0px rgba(10, 32, 139, 0.05)",
  },
}
