/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Factory {
  export type ERC20SlimProtectionDetailsStruct = {
    protectionAddress: AddressLike;
    primaryWallet: AddressLike;
    backupWallet: AddressLike;
    timelapse: BigNumberish;
  };

  export type ERC20SlimProtectionDetailsStructOutput = [
    protectionAddress: string,
    primaryWallet: string,
    backupWallet: string,
    timelapse: bigint
  ] & {
    protectionAddress: string;
    primaryWallet: string;
    backupWallet: string;
    timelapse: bigint;
  };

  export type NFTProtectionDetailsStruct = {
    protectionAddress: AddressLike;
    primaryWallet: AddressLike;
    backupWallet: AddressLike;
    timelapse: BigNumberish;
    erc721Assets: NFTProtectionDelegate.NFTAssetStruct[];
    erc1155Assets: NFTProtectionDelegate.NFTAssetStruct[];
  };

  export type NFTProtectionDetailsStructOutput = [
    protectionAddress: string,
    primaryWallet: string,
    backupWallet: string,
    timelapse: bigint,
    erc721Assets: NFTProtectionDelegate.NFTAssetStructOutput[],
    erc1155Assets: NFTProtectionDelegate.NFTAssetStructOutput[]
  ] & {
    protectionAddress: string;
    primaryWallet: string;
    backupWallet: string;
    timelapse: bigint;
    erc721Assets: NFTProtectionDelegate.NFTAssetStructOutput[];
    erc1155Assets: NFTProtectionDelegate.NFTAssetStructOutput[];
  };

  export type ProtectionDetailsStruct = {
    protectionAddress: AddressLike;
    primaryWallet: AddressLike;
    backupWallet: AddressLike;
    timelapse: BigNumberish;
    erc20Assets: AddressLike[];
  };

  export type ProtectionDetailsStructOutput = [
    protectionAddress: string,
    primaryWallet: string,
    backupWallet: string,
    timelapse: bigint,
    erc20Assets: string[]
  ] & {
    protectionAddress: string;
    primaryWallet: string;
    backupWallet: string;
    timelapse: bigint;
    erc20Assets: string[];
  };
}

export declare namespace NFTProtectionDelegate {
  export type NFTAssetStruct = { asset: AddressLike; ids: BigNumberish[] };

  export type NFTAssetStructOutput = [asset: string, ids: bigint[]] & {
    asset: string;
    ids: bigint[];
  };
}

export interface FactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateNFTTransferGas"
      | "calculateTransferCosts"
      | "getAllERC20SlimProtectionContracts"
      | "getAllNFTProtectionContracts"
      | "getAllProtectionContracts"
      | "getERC20SlimProtectionContractDetails"
      | "getERC20SlimProtectionContracts"
      | "getNFTProtectionContractDetails"
      | "getNFTProtectionContracts"
      | "getProtectionContractDetails"
      | "getProtectionContracts"
      | "getRegistrationFee"
      | "owner"
      | "register"
      | "registerERC20Slim"
      | "registerNFT"
      | "registerNFTWithAssets"
      | "removeERC20SlimProtection"
      | "removeNFTProtection"
      | "removeProtection"
      | "renounceOwnership"
      | "sendBalanceToOwner"
      | "setRegistrationFee"
      | "transferAssetsFor"
      | "transferERC20SlimAssetsFor"
      | "transferNFTAssetsFor"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetProtectionRegistered"
      | "ERC20SlimAssetProtectionRegistered"
      | "NFTAssetProtectionRegistered"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateNFTTransferGas",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTransferCosts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllERC20SlimProtectionContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllNFTProtectionContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllProtectionContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getERC20SlimProtectionContractDetails",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getERC20SlimProtectionContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNFTProtectionContractDetails",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNFTProtectionContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProtectionContractDetails",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProtectionContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRegistrationFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressLike, BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "registerERC20Slim",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerNFT",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerNFTWithAssets",
    values: [
      AddressLike,
      BigNumberish,
      AddressLike[],
      BigNumberish[][],
      AddressLike[],
      BigNumberish[][]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeERC20SlimProtection",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeNFTProtection",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeProtection",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendBalanceToOwner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegistrationFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAssetsFor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferERC20SlimAssetsFor",
    values: [AddressLike, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferNFTAssetsFor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateNFTTransferGas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateTransferCosts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllERC20SlimProtectionContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllNFTProtectionContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllProtectionContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getERC20SlimProtectionContractDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getERC20SlimProtectionContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNFTProtectionContractDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNFTProtectionContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProtectionContractDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProtectionContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegistrationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerERC20Slim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerNFTWithAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeERC20SlimProtection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeNFTProtection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeProtection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendBalanceToOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRegistrationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAssetsFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferERC20SlimAssetsFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferNFTAssetsFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AssetProtectionRegisteredEvent {
  export type InputTuple = [
    protectionAddress: AddressLike,
    primaryWallet: AddressLike,
    backupWallet: AddressLike,
    timelapse: BigNumberish,
    erc20Assets: AddressLike[]
  ];
  export type OutputTuple = [
    protectionAddress: string,
    primaryWallet: string,
    backupWallet: string,
    timelapse: bigint,
    erc20Assets: string[]
  ];
  export interface OutputObject {
    protectionAddress: string;
    primaryWallet: string;
    backupWallet: string;
    timelapse: bigint;
    erc20Assets: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ERC20SlimAssetProtectionRegisteredEvent {
  export type InputTuple = [
    protectionAddress: AddressLike,
    primaryWallet: AddressLike,
    backupWallet: AddressLike,
    timelapse: BigNumberish
  ];
  export type OutputTuple = [
    protectionAddress: string,
    primaryWallet: string,
    backupWallet: string,
    timelapse: bigint
  ];
  export interface OutputObject {
    protectionAddress: string;
    primaryWallet: string;
    backupWallet: string;
    timelapse: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTAssetProtectionRegisteredEvent {
  export type InputTuple = [
    protectionAddress: AddressLike,
    primaryWallet: AddressLike,
    backupWallet: AddressLike,
    timelapse: BigNumberish
  ];
  export type OutputTuple = [
    protectionAddress: string,
    primaryWallet: string,
    backupWallet: string,
    timelapse: bigint
  ];
  export interface OutputObject {
    protectionAddress: string;
    primaryWallet: string;
    backupWallet: string;
    timelapse: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Factory extends BaseContract {
  connect(runner?: ContractRunner | null): Factory;
  waitForDeployment(): Promise<this>;

  interface: FactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateNFTTransferGas: TypedContractMethod<
    [erc721Count: BigNumberish, erc1155Count: BigNumberish],
    [bigint],
    "view"
  >;

  calculateTransferCosts: TypedContractMethod<
    [erc20ContractCount: BigNumberish],
    [bigint],
    "view"
  >;

  getAllERC20SlimProtectionContracts: TypedContractMethod<
    [],
    [Factory.ERC20SlimProtectionDetailsStructOutput[]],
    "view"
  >;

  getAllNFTProtectionContracts: TypedContractMethod<
    [],
    [Factory.NFTProtectionDetailsStructOutput[]],
    "view"
  >;

  getAllProtectionContracts: TypedContractMethod<
    [],
    [Factory.ProtectionDetailsStructOutput[]],
    "view"
  >;

  getERC20SlimProtectionContractDetails: TypedContractMethod<
    [protectionAddress: AddressLike],
    [Factory.ERC20SlimProtectionDetailsStructOutput],
    "view"
  >;

  getERC20SlimProtectionContracts: TypedContractMethod<[], [string[]], "view">;

  getNFTProtectionContractDetails: TypedContractMethod<
    [protectionAddress: AddressLike],
    [Factory.NFTProtectionDetailsStructOutput],
    "view"
  >;

  getNFTProtectionContracts: TypedContractMethod<[], [string[]], "view">;

  getProtectionContractDetails: TypedContractMethod<
    [protectionAddress: AddressLike],
    [Factory.ProtectionDetailsStructOutput],
    "view"
  >;

  getProtectionContracts: TypedContractMethod<[], [string[]], "view">;

  getRegistrationFee: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  register: TypedContractMethod<
    [
      _backupWallet: AddressLike,
      _timelapse: BigNumberish,
      _erc20Assets: AddressLike[]
    ],
    [void],
    "payable"
  >;

  registerERC20Slim: TypedContractMethod<
    [_backupWallet: AddressLike, _timelapse: BigNumberish],
    [void],
    "payable"
  >;

  registerNFT: TypedContractMethod<
    [_backupWallet: AddressLike, _timelapse: BigNumberish],
    [void],
    "payable"
  >;

  registerNFTWithAssets: TypedContractMethod<
    [
      _backupWallet: AddressLike,
      _timelapse: BigNumberish,
      _erc721Assets: AddressLike[],
      _erc721TokenIds: BigNumberish[][],
      _erc1155Assets: AddressLike[],
      _erc1155TokenIds: BigNumberish[][]
    ],
    [void],
    "payable"
  >;

  removeERC20SlimProtection: TypedContractMethod<
    [protectionAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  removeNFTProtection: TypedContractMethod<
    [protectionAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  removeProtection: TypedContractMethod<
    [protectionAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sendBalanceToOwner: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRegistrationFee: TypedContractMethod<
    [_registrationFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferAssetsFor: TypedContractMethod<
    [protectionAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  transferERC20SlimAssetsFor: TypedContractMethod<
    [
      protectionAddress: AddressLike,
      _erc20Assets: AddressLike[],
      _amounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  transferNFTAssetsFor: TypedContractMethod<
    [protectionAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateNFTTransferGas"
  ): TypedContractMethod<
    [erc721Count: BigNumberish, erc1155Count: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateTransferCosts"
  ): TypedContractMethod<[erc20ContractCount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllERC20SlimProtectionContracts"
  ): TypedContractMethod<
    [],
    [Factory.ERC20SlimProtectionDetailsStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllNFTProtectionContracts"
  ): TypedContractMethod<
    [],
    [Factory.NFTProtectionDetailsStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllProtectionContracts"
  ): TypedContractMethod<[], [Factory.ProtectionDetailsStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getERC20SlimProtectionContractDetails"
  ): TypedContractMethod<
    [protectionAddress: AddressLike],
    [Factory.ERC20SlimProtectionDetailsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getERC20SlimProtectionContracts"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getNFTProtectionContractDetails"
  ): TypedContractMethod<
    [protectionAddress: AddressLike],
    [Factory.NFTProtectionDetailsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNFTProtectionContracts"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getProtectionContractDetails"
  ): TypedContractMethod<
    [protectionAddress: AddressLike],
    [Factory.ProtectionDetailsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProtectionContracts"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRegistrationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [
      _backupWallet: AddressLike,
      _timelapse: BigNumberish,
      _erc20Assets: AddressLike[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "registerERC20Slim"
  ): TypedContractMethod<
    [_backupWallet: AddressLike, _timelapse: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "registerNFT"
  ): TypedContractMethod<
    [_backupWallet: AddressLike, _timelapse: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "registerNFTWithAssets"
  ): TypedContractMethod<
    [
      _backupWallet: AddressLike,
      _timelapse: BigNumberish,
      _erc721Assets: AddressLike[],
      _erc721TokenIds: BigNumberish[][],
      _erc1155Assets: AddressLike[],
      _erc1155TokenIds: BigNumberish[][]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "removeERC20SlimProtection"
  ): TypedContractMethod<
    [protectionAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeNFTProtection"
  ): TypedContractMethod<
    [protectionAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeProtection"
  ): TypedContractMethod<
    [protectionAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sendBalanceToOwner"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRegistrationFee"
  ): TypedContractMethod<
    [_registrationFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferAssetsFor"
  ): TypedContractMethod<
    [protectionAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferERC20SlimAssetsFor"
  ): TypedContractMethod<
    [
      protectionAddress: AddressLike,
      _erc20Assets: AddressLike[],
      _amounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferNFTAssetsFor"
  ): TypedContractMethod<
    [protectionAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AssetProtectionRegistered"
  ): TypedContractEvent<
    AssetProtectionRegisteredEvent.InputTuple,
    AssetProtectionRegisteredEvent.OutputTuple,
    AssetProtectionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ERC20SlimAssetProtectionRegistered"
  ): TypedContractEvent<
    ERC20SlimAssetProtectionRegisteredEvent.InputTuple,
    ERC20SlimAssetProtectionRegisteredEvent.OutputTuple,
    ERC20SlimAssetProtectionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "NFTAssetProtectionRegistered"
  ): TypedContractEvent<
    NFTAssetProtectionRegisteredEvent.InputTuple,
    NFTAssetProtectionRegisteredEvent.OutputTuple,
    NFTAssetProtectionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AssetProtectionRegistered(address,address,address,uint256,address[])": TypedContractEvent<
      AssetProtectionRegisteredEvent.InputTuple,
      AssetProtectionRegisteredEvent.OutputTuple,
      AssetProtectionRegisteredEvent.OutputObject
    >;
    AssetProtectionRegistered: TypedContractEvent<
      AssetProtectionRegisteredEvent.InputTuple,
      AssetProtectionRegisteredEvent.OutputTuple,
      AssetProtectionRegisteredEvent.OutputObject
    >;

    "ERC20SlimAssetProtectionRegistered(address,address,address,uint256)": TypedContractEvent<
      ERC20SlimAssetProtectionRegisteredEvent.InputTuple,
      ERC20SlimAssetProtectionRegisteredEvent.OutputTuple,
      ERC20SlimAssetProtectionRegisteredEvent.OutputObject
    >;
    ERC20SlimAssetProtectionRegistered: TypedContractEvent<
      ERC20SlimAssetProtectionRegisteredEvent.InputTuple,
      ERC20SlimAssetProtectionRegisteredEvent.OutputTuple,
      ERC20SlimAssetProtectionRegisteredEvent.OutputObject
    >;

    "NFTAssetProtectionRegistered(address,address,address,uint256)": TypedContractEvent<
      NFTAssetProtectionRegisteredEvent.InputTuple,
      NFTAssetProtectionRegisteredEvent.OutputTuple,
      NFTAssetProtectionRegisteredEvent.OutputObject
    >;
    NFTAssetProtectionRegistered: TypedContractEvent<
      NFTAssetProtectionRegisteredEvent.InputTuple,
      NFTAssetProtectionRegisteredEvent.OutputTuple,
      NFTAssetProtectionRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
