/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./Mocks";
export type { mocks };
export type { ERC20ProtectionDelegate } from "./ERC20ProtectionDelegate";
export type { ERC20ProtectionSlim } from "./ERC20ProtectionSlim";
export type { Factory } from "./Factory";
export type { NFTProtectionDelegate } from "./NFTProtectionDelegate";
export type { NFTProtectionSlim } from "./NFTProtectionSlim";
export type { ProtectionDelegate } from "./ProtectionDelegate";
export type { ProtectionSlim } from "./ProtectionSlim";
