/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace NFTProtectionDelegate {
  export type NFTAssetStruct = { asset: AddressLike; ids: BigNumberish[] };

  export type NFTAssetStructOutput = [asset: string, ids: bigint[]] & {
    asset: string;
    ids: bigint[];
  };
}

export interface NFTProtectionDelegateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addNewAssets"
      | "addOrUpdateAssets"
      | "assetsTransferred"
      | "backupWallet"
      | "cancel"
      | "getAllProtectedAssets"
      | "getERC1155Assets"
      | "getERC721Assets"
      | "isAssetProtected"
      | "primaryWallet"
      | "recoverAssets"
      | "removeProtectedAssets"
      | "setTimelapse"
      | "timelapse"
      | "transferAssets"
      | "updateERC1155Ids"
      | "updateERC721TokenIds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "NFT_AssetProtectionCancelled"
      | "NFT_AssetsAdded"
      | "NFT_AssetsRecovered"
      | "NFT_AssetsRemoved"
      | "NFT_AssetsTransferred"
      | "NFT_IdsUpdated"
      | "NFT_TimelapseUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addNewAssets",
    values: [AddressLike[], BigNumberish[][], AddressLike[], BigNumberish[][]]
  ): string;
  encodeFunctionData(
    functionFragment: "addOrUpdateAssets",
    values: [
      AddressLike[],
      BigNumberish[][],
      AddressLike[],
      BigNumberish[][],
      AddressLike[],
      BigNumberish[][],
      AddressLike[],
      BigNumberish[][]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "assetsTransferred",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "backupWallet",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "cancel", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllProtectedAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getERC1155Assets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getERC721Assets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAssetProtected",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "primaryWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recoverAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeProtectedAssets",
    values: [AddressLike[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimelapse",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "timelapse", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateERC1155Ids",
    values: [AddressLike[], BigNumberish[][]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateERC721TokenIds",
    values: [AddressLike[], BigNumberish[][]]
  ): string;

  decodeFunctionResult(
    functionFragment: "addNewAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addOrUpdateAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetsTransferred",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "backupWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllProtectedAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getERC1155Assets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getERC721Assets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAssetProtected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "primaryWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeProtectedAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimelapse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelapse", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateERC1155Ids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateERC721TokenIds",
    data: BytesLike
  ): Result;
}

export namespace NFT_AssetProtectionCancelledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFT_AssetsAddedEvent {
  export type InputTuple = [
    erc721Assets: AddressLike[],
    erc721Ids: BigNumberish[][],
    erc1155Assets: AddressLike[],
    erc1155Ids: BigNumberish[][]
  ];
  export type OutputTuple = [
    erc721Assets: string[],
    erc721Ids: bigint[][],
    erc1155Assets: string[],
    erc1155Ids: bigint[][]
  ];
  export interface OutputObject {
    erc721Assets: string[];
    erc721Ids: bigint[][];
    erc1155Assets: string[];
    erc1155Ids: bigint[][];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFT_AssetsRecoveredEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFT_AssetsRemovedEvent {
  export type InputTuple = [
    erc721Assets: AddressLike[],
    erc1155Assets: AddressLike[]
  ];
  export type OutputTuple = [erc721Assets: string[], erc1155Assets: string[]];
  export interface OutputObject {
    erc721Assets: string[];
    erc1155Assets: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFT_AssetsTransferredEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFT_IdsUpdatedEvent {
  export type InputTuple = [
    flag: BigNumberish,
    assets: AddressLike[],
    ids: BigNumberish[][]
  ];
  export type OutputTuple = [flag: bigint, assets: string[], ids: bigint[][]];
  export interface OutputObject {
    flag: bigint;
    assets: string[];
    ids: bigint[][];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFT_TimelapseUpdatedEvent {
  export type InputTuple = [
    oldTimelapse: BigNumberish,
    newTimelapse: BigNumberish
  ];
  export type OutputTuple = [oldTimelapse: bigint, newTimelapse: bigint];
  export interface OutputObject {
    oldTimelapse: bigint;
    newTimelapse: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NFTProtectionDelegate extends BaseContract {
  connect(runner?: ContractRunner | null): NFTProtectionDelegate;
  waitForDeployment(): Promise<this>;

  interface: NFTProtectionDelegateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addNewAssets: TypedContractMethod<
    [
      _erc721Assets: AddressLike[],
      _erc721TokenIds: BigNumberish[][],
      _erc1155Assets: AddressLike[],
      _erc1155TokenIds: BigNumberish[][]
    ],
    [void],
    "payable"
  >;

  addOrUpdateAssets: TypedContractMethod<
    [
      _erc721Assets: AddressLike[],
      _erc721TokenIds: BigNumberish[][],
      _erc1155Assets: AddressLike[],
      _erc1155TokenIds: BigNumberish[][],
      _updErc721Assets: AddressLike[],
      _updErc721TokenIds: BigNumberish[][],
      _updErc1155Assets: AddressLike[],
      _updErc1155TokenIds: BigNumberish[][]
    ],
    [void],
    "payable"
  >;

  assetsTransferred: TypedContractMethod<[], [boolean], "view">;

  backupWallet: TypedContractMethod<[], [string], "view">;

  cancel: TypedContractMethod<[], [void], "nonpayable">;

  getAllProtectedAssets: TypedContractMethod<[], [string[]], "view">;

  getERC1155Assets: TypedContractMethod<
    [],
    [NFTProtectionDelegate.NFTAssetStructOutput[]],
    "view"
  >;

  getERC721Assets: TypedContractMethod<
    [],
    [NFTProtectionDelegate.NFTAssetStructOutput[]],
    "view"
  >;

  isAssetProtected: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  primaryWallet: TypedContractMethod<[], [string], "view">;

  recoverAssets: TypedContractMethod<[], [void], "nonpayable">;

  removeProtectedAssets: TypedContractMethod<
    [_erc721Assets: AddressLike[], _erc1155Assets: AddressLike[]],
    [void],
    "nonpayable"
  >;

  setTimelapse: TypedContractMethod<
    [_timelapse: BigNumberish],
    [void],
    "payable"
  >;

  timelapse: TypedContractMethod<[], [bigint], "view">;

  transferAssets: TypedContractMethod<[], [void], "nonpayable">;

  updateERC1155Ids: TypedContractMethod<
    [_assets: AddressLike[], _ids: BigNumberish[][]],
    [void],
    "payable"
  >;

  updateERC721TokenIds: TypedContractMethod<
    [_assets: AddressLike[], _tokenIds: BigNumberish[][]],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addNewAssets"
  ): TypedContractMethod<
    [
      _erc721Assets: AddressLike[],
      _erc721TokenIds: BigNumberish[][],
      _erc1155Assets: AddressLike[],
      _erc1155TokenIds: BigNumberish[][]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "addOrUpdateAssets"
  ): TypedContractMethod<
    [
      _erc721Assets: AddressLike[],
      _erc721TokenIds: BigNumberish[][],
      _erc1155Assets: AddressLike[],
      _erc1155TokenIds: BigNumberish[][],
      _updErc721Assets: AddressLike[],
      _updErc721TokenIds: BigNumberish[][],
      _updErc1155Assets: AddressLike[],
      _updErc1155TokenIds: BigNumberish[][]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "assetsTransferred"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "backupWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllProtectedAssets"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getERC1155Assets"
  ): TypedContractMethod<
    [],
    [NFTProtectionDelegate.NFTAssetStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getERC721Assets"
  ): TypedContractMethod<
    [],
    [NFTProtectionDelegate.NFTAssetStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAssetProtected"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "primaryWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recoverAssets"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeProtectedAssets"
  ): TypedContractMethod<
    [_erc721Assets: AddressLike[], _erc1155Assets: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTimelapse"
  ): TypedContractMethod<[_timelapse: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "timelapse"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferAssets"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateERC1155Ids"
  ): TypedContractMethod<
    [_assets: AddressLike[], _ids: BigNumberish[][]],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "updateERC721TokenIds"
  ): TypedContractMethod<
    [_assets: AddressLike[], _tokenIds: BigNumberish[][]],
    [void],
    "payable"
  >;

  getEvent(
    key: "NFT_AssetProtectionCancelled"
  ): TypedContractEvent<
    NFT_AssetProtectionCancelledEvent.InputTuple,
    NFT_AssetProtectionCancelledEvent.OutputTuple,
    NFT_AssetProtectionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "NFT_AssetsAdded"
  ): TypedContractEvent<
    NFT_AssetsAddedEvent.InputTuple,
    NFT_AssetsAddedEvent.OutputTuple,
    NFT_AssetsAddedEvent.OutputObject
  >;
  getEvent(
    key: "NFT_AssetsRecovered"
  ): TypedContractEvent<
    NFT_AssetsRecoveredEvent.InputTuple,
    NFT_AssetsRecoveredEvent.OutputTuple,
    NFT_AssetsRecoveredEvent.OutputObject
  >;
  getEvent(
    key: "NFT_AssetsRemoved"
  ): TypedContractEvent<
    NFT_AssetsRemovedEvent.InputTuple,
    NFT_AssetsRemovedEvent.OutputTuple,
    NFT_AssetsRemovedEvent.OutputObject
  >;
  getEvent(
    key: "NFT_AssetsTransferred"
  ): TypedContractEvent<
    NFT_AssetsTransferredEvent.InputTuple,
    NFT_AssetsTransferredEvent.OutputTuple,
    NFT_AssetsTransferredEvent.OutputObject
  >;
  getEvent(
    key: "NFT_IdsUpdated"
  ): TypedContractEvent<
    NFT_IdsUpdatedEvent.InputTuple,
    NFT_IdsUpdatedEvent.OutputTuple,
    NFT_IdsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NFT_TimelapseUpdated"
  ): TypedContractEvent<
    NFT_TimelapseUpdatedEvent.InputTuple,
    NFT_TimelapseUpdatedEvent.OutputTuple,
    NFT_TimelapseUpdatedEvent.OutputObject
  >;

  filters: {
    "NFT_AssetProtectionCancelled()": TypedContractEvent<
      NFT_AssetProtectionCancelledEvent.InputTuple,
      NFT_AssetProtectionCancelledEvent.OutputTuple,
      NFT_AssetProtectionCancelledEvent.OutputObject
    >;
    NFT_AssetProtectionCancelled: TypedContractEvent<
      NFT_AssetProtectionCancelledEvent.InputTuple,
      NFT_AssetProtectionCancelledEvent.OutputTuple,
      NFT_AssetProtectionCancelledEvent.OutputObject
    >;

    "NFT_AssetsAdded(address[],uint256[][],address[],uint256[][])": TypedContractEvent<
      NFT_AssetsAddedEvent.InputTuple,
      NFT_AssetsAddedEvent.OutputTuple,
      NFT_AssetsAddedEvent.OutputObject
    >;
    NFT_AssetsAdded: TypedContractEvent<
      NFT_AssetsAddedEvent.InputTuple,
      NFT_AssetsAddedEvent.OutputTuple,
      NFT_AssetsAddedEvent.OutputObject
    >;

    "NFT_AssetsRecovered()": TypedContractEvent<
      NFT_AssetsRecoveredEvent.InputTuple,
      NFT_AssetsRecoveredEvent.OutputTuple,
      NFT_AssetsRecoveredEvent.OutputObject
    >;
    NFT_AssetsRecovered: TypedContractEvent<
      NFT_AssetsRecoveredEvent.InputTuple,
      NFT_AssetsRecoveredEvent.OutputTuple,
      NFT_AssetsRecoveredEvent.OutputObject
    >;

    "NFT_AssetsRemoved(address[],address[])": TypedContractEvent<
      NFT_AssetsRemovedEvent.InputTuple,
      NFT_AssetsRemovedEvent.OutputTuple,
      NFT_AssetsRemovedEvent.OutputObject
    >;
    NFT_AssetsRemoved: TypedContractEvent<
      NFT_AssetsRemovedEvent.InputTuple,
      NFT_AssetsRemovedEvent.OutputTuple,
      NFT_AssetsRemovedEvent.OutputObject
    >;

    "NFT_AssetsTransferred()": TypedContractEvent<
      NFT_AssetsTransferredEvent.InputTuple,
      NFT_AssetsTransferredEvent.OutputTuple,
      NFT_AssetsTransferredEvent.OutputObject
    >;
    NFT_AssetsTransferred: TypedContractEvent<
      NFT_AssetsTransferredEvent.InputTuple,
      NFT_AssetsTransferredEvent.OutputTuple,
      NFT_AssetsTransferredEvent.OutputObject
    >;

    "NFT_IdsUpdated(uint256,address[],uint256[][])": TypedContractEvent<
      NFT_IdsUpdatedEvent.InputTuple,
      NFT_IdsUpdatedEvent.OutputTuple,
      NFT_IdsUpdatedEvent.OutputObject
    >;
    NFT_IdsUpdated: TypedContractEvent<
      NFT_IdsUpdatedEvent.InputTuple,
      NFT_IdsUpdatedEvent.OutputTuple,
      NFT_IdsUpdatedEvent.OutputObject
    >;

    "NFT_TimelapseUpdated(uint256,uint256)": TypedContractEvent<
      NFT_TimelapseUpdatedEvent.InputTuple,
      NFT_TimelapseUpdatedEvent.OutputTuple,
      NFT_TimelapseUpdatedEvent.OutputObject
    >;
    NFT_TimelapseUpdated: TypedContractEvent<
      NFT_TimelapseUpdatedEvent.InputTuple,
      NFT_TimelapseUpdatedEvent.OutputTuple,
      NFT_TimelapseUpdatedEvent.OutputObject
    >;
  };
}
