/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface NFTProtectionSlimInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assetsTransferred"
      | "backupWallet"
      | "isAssetProtected"
      | "primaryWallet"
      | "timelapse"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "assetsTransferred",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "backupWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAssetProtected",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "primaryWallet",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "timelapse", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "assetsTransferred",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "backupWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAssetProtected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "primaryWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelapse", data: BytesLike): Result;
}

export interface NFTProtectionSlim extends BaseContract {
  connect(runner?: ContractRunner | null): NFTProtectionSlim;
  waitForDeployment(): Promise<this>;

  interface: NFTProtectionSlimInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assetsTransferred: TypedContractMethod<[], [boolean], "view">;

  backupWallet: TypedContractMethod<[], [string], "view">;

  isAssetProtected: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  primaryWallet: TypedContractMethod<[], [string], "view">;

  timelapse: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assetsTransferred"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "backupWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isAssetProtected"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "primaryWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "timelapse"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
