/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ProtectionDelegateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assetsTransferred"
      | "backupWallet"
      | "cancel"
      | "factory"
      | "getERC20Assets"
      | "primaryWallet"
      | "recoverAssets"
      | "timelapse"
      | "transferAssets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PC_AssetProtectionCancelled"
      | "PC_AssetsRecovered"
      | "PC_AssetsTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assetsTransferred",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "backupWallet",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "cancel", values?: undefined): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getERC20Assets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "primaryWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recoverAssets",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "timelapse", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferAssets",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "assetsTransferred",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "backupWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getERC20Assets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "primaryWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelapse", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferAssets",
    data: BytesLike
  ): Result;
}

export namespace PC_AssetProtectionCancelledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PC_AssetsRecoveredEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PC_AssetsTransferredEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProtectionDelegate extends BaseContract {
  connect(runner?: ContractRunner | null): ProtectionDelegate;
  waitForDeployment(): Promise<this>;

  interface: ProtectionDelegateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assetsTransferred: TypedContractMethod<[], [boolean], "view">;

  backupWallet: TypedContractMethod<[], [string], "view">;

  cancel: TypedContractMethod<[], [void], "nonpayable">;

  factory: TypedContractMethod<[], [string], "view">;

  getERC20Assets: TypedContractMethod<[], [string[]], "view">;

  primaryWallet: TypedContractMethod<[], [string], "view">;

  recoverAssets: TypedContractMethod<[], [void], "nonpayable">;

  timelapse: TypedContractMethod<[], [bigint], "view">;

  transferAssets: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assetsTransferred"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "backupWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getERC20Assets"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "primaryWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recoverAssets"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "timelapse"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferAssets"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "PC_AssetProtectionCancelled"
  ): TypedContractEvent<
    PC_AssetProtectionCancelledEvent.InputTuple,
    PC_AssetProtectionCancelledEvent.OutputTuple,
    PC_AssetProtectionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PC_AssetsRecovered"
  ): TypedContractEvent<
    PC_AssetsRecoveredEvent.InputTuple,
    PC_AssetsRecoveredEvent.OutputTuple,
    PC_AssetsRecoveredEvent.OutputObject
  >;
  getEvent(
    key: "PC_AssetsTransferred"
  ): TypedContractEvent<
    PC_AssetsTransferredEvent.InputTuple,
    PC_AssetsTransferredEvent.OutputTuple,
    PC_AssetsTransferredEvent.OutputObject
  >;

  filters: {
    "PC_AssetProtectionCancelled()": TypedContractEvent<
      PC_AssetProtectionCancelledEvent.InputTuple,
      PC_AssetProtectionCancelledEvent.OutputTuple,
      PC_AssetProtectionCancelledEvent.OutputObject
    >;
    PC_AssetProtectionCancelled: TypedContractEvent<
      PC_AssetProtectionCancelledEvent.InputTuple,
      PC_AssetProtectionCancelledEvent.OutputTuple,
      PC_AssetProtectionCancelledEvent.OutputObject
    >;

    "PC_AssetsRecovered()": TypedContractEvent<
      PC_AssetsRecoveredEvent.InputTuple,
      PC_AssetsRecoveredEvent.OutputTuple,
      PC_AssetsRecoveredEvent.OutputObject
    >;
    PC_AssetsRecovered: TypedContractEvent<
      PC_AssetsRecoveredEvent.InputTuple,
      PC_AssetsRecoveredEvent.OutputTuple,
      PC_AssetsRecoveredEvent.OutputObject
    >;

    "PC_AssetsTransferred()": TypedContractEvent<
      PC_AssetsTransferredEvent.InputTuple,
      PC_AssetsTransferredEvent.OutputTuple,
      PC_AssetsTransferredEvent.OutputObject
    >;
    PC_AssetsTransferred: TypedContractEvent<
      PC_AssetsTransferredEvent.InputTuple,
      PC_AssetsTransferredEvent.OutputTuple,
      PC_AssetsTransferredEvent.OutputObject
    >;
  };
}
